routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();
Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', 'LoginController@showLoginView')->name('login');
        Route::post('/login', 'LoginController@Login')->name('login.submit');
        Route::get('/logout', 'LoginController@logout')->name('logout');
    });
    Route::get('/home', 'adminController@index')->name('adminhome');
    Route::get('/', 'adminController@index')->name('home');
    Route::resource('/permissions', 'permissionsController');
    Route::resource('/users', 'usersController');
    Route::resource('/roles', 'rolesController');

    Route::resource('/division', 'divisionController');

    Route::post('/departamento/{idparent}', 'divisionController@storeDepartamento');
    Route::put('/departamento/{idparent}', 'divisionController@updateDepartamento');
    Route::delete('/division/departamento/{idparent}', 'divisionController@destroyDepartamento');

    Route::post('/seccion/{idparent}', 'divisionController@storeSeccion');
    Route::put('/seccion/{idparent}', 'divisionController@updateSeccion');
    Route::delete('/division/seccion/{idparent}', 'divisionController@destroySeccion');

    Route::post('/oficina/{idparent}', 'divisionController@storeOficina');
    Route::put('/oficina/{idparent}', 'divisionController@updateOficina');
    Route::delete('/division/oficina/{idparent}', 'divisionController@destroyOficina');

    Route::post('/delegacion/{idparent}', 'divisionController@storeDelegacion');
    Route::put('/delegacion/{idparent}', 'divisionController@updateDelegacion');
    Route::delete('/division/delegacion/{idparent}', 'divisionController@destroyDelegacion');


    Route::resource('/usuariosFront', 'usersFrontController');

    Route::resource('/accesosFront', 'accessFrontController');
});


Route::namespace('AuthFront')->group(function(){
    Route::get('/login', 'LoginController@showLoginView')->name('login');
    Route::post('/login', 'LoginController@Login')->name('login.submit');
    Route::get('/logout', 'LoginController@logout')->name('logout');
});

Route::get('/', 'HomeController@index')->name('home')->middleware('authtimeout');
Route::get('/home', 'HomeController@index')->middleware('authtimeout');

Route::resource('/solicitudes', 'SolicitudesController')->middleware('authtimeout');

Route::resource('/requerimiento_MP', 'RequerimientoMPController')->middleware('authtimeout');

Route::resource('/requerimiento_', 'RequerimientosController')->middleware('authtimeout');




// View::composer('*', function($view){
//     $view->alertas = Controller::list_alertas();
// });

app/Http/Controllers/Admin/accessFrontController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\adminModels\frontAccessModel;

class accessFrontController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->indexUrl= 'admin.accesosFront.index';
    }

    public function index(){
      $accesos = frontAccessModel::get();

      return view('admin.accessFront.show',
            ['menubar'=> $this->list_sidebar(),
             'accesos' => $accesos
            ]);

    }

    public function store(Request $request) {
      $validator = $request->validate([
          'name' => 'required',
          'route' => 'required',
      ]);

      $access = new frontAccessModel;
      $data = $request->only($access->getFillable());
      // $data["publc"] = (isset($data["publc"])?1:0);
      $access->fill($data)->save();
      return redirect()->route($this->indexUrl)
      ->with('success','Guardado correctamente!');
    }


    public function destroy($id) {
      frontAccessModel::destroy($id);
      return redirect()->route($this->indexUrl)
      ->with('warning','Borrado correctamente!');
    }


    public function update(Request $request, $id) {
      $model = new frontAccessModel;
      $access = $model::find($id);
      $data = $request->only($model->getFillable());
      // $data["publc"] = (isset($data["publc"])?1:0);
      $access->fill($data)->save();
      // dd($access);
      // return redirect('pages/aracislemler/'.$vehicle->id);
      return redirect()->route($this->indexUrl)
      ->with('info','Actualizado correctamente!');
    }
}

resources/views/admin/accessFront/show.blade.php
@extends('admin.layouts.master')
@section('main-content')
<script type="text/javascript">
  var kad={0:{type:"hddn",nm:"_token",vl:'{{ csrf_token() }}'},
          1:{type:"txt",tl:"Nombre",nm:"name",elv:"0",nxt:6},
          2:{type:"txt",tl:"Url",nm:"route",elv:"1",nxt:6},
          // 3:{type:"chkbxstyl",tl:"Publico",nm:"publc",vl:[["1",'<span id="stat"></span>']],
          //    elv:"2",add:'onclick="checar(this,0);" omit="T"',nxt:6},
          3:{type:"txt",tl:"Icono",id:"imag",nm:"icon",elv:"2", add:'onclick="flotingblank(this);" readonly',nxt:6},
          4:{type:"txt",tl:"Grupo",nm:"group",elv:"3"}};

  var conform={action:"{{route('admin.accesosFront.store')}}"}
    valdis={clase:"red",text:1,checkbox:1,radio:1};

</script>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    <a href="javascript:"class="" onclick="newfloatv2(kad);">
                        <i class="ion-ios7-plus-outline"></i>&nbsp;&nbsp;Nuevo acceso
                    </a>
                </h3>
            </div>

            <div class="card-body">
                <div class="table-responsive">
                    <table i class="display table table-striped table-bordered" cellspacing="0" width="100%" style="width:100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Grupo</th>
                                <th>Título</th>
                                <th>Ícono</th>
                                <th>Archivo</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>

                        <tbody>
                            @php
                                $criti = [];
                            @endphp
                            @foreach ($accesos as $a)
                                <tr>
                                    <td>{{ $loop->index + 1 }}</td>
                                    <td class="hidden-xs">{{ $a->group }}</td>
                                    <td>{{ $a->name }}</td>
                                    <td><i class="text-20 {{ $a->icon }}"></i></td>
                                    <td class="hidden-xs">{{ $a->route }}</td>

                                    <td class="td-actions  text-left">
                                        <a href="javascript:" class=""
                                            onclick="modifyfloat('{{$a->id}}',kad,criteria);">
                                            <i class="text-20"data-feather="edit-3"></i>
                                        </a>
                                        <a href="javascript:"
                                            onclick="deleteD('{{$a->id}}','{{ csrf_token() }}');">
                                            <i class="text-12" data-feather="trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            @php
                                $criti[$a->id] = [$a->name,
                                    $a->route,
                                    $a->icon,
                                    $a->group,
                                ];
                            @endphp
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var criteria = <?=json_encode($criti)?>;

    function fillimg(sto)
    {
        $("#imag").val(sto);
        flotantecloseblank();
    }
</script>

@component('components.messagesForm')
@endcomponent

@endsection